import 'package:flutter/material.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedEndereodeemailWidget1.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedConfirmeasenhaWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedDigiteseuemailWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedIconocultarsenha1Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedCriarContaWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedNomecompletoWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedCancelarWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedConfirmesuasenhaWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedDigitesuasenhaWidget1.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedIColetaContainer2Widget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedDigiteseunomeWidget.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedSenhaWidget1.dart';
import 'package:flutterapp/icoletaapp/generatedteladecadastrowidget/generated/GeneratedIconocultarsenha2Widget.dart';

/* Frame Tela de Cadastro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeCadastroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(10.0),
      child: Container(
        width: 320.0,
        height: 568.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(10.0),
                child: Container(
                  color: Color.fromARGB(255, 66, 190, 165),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 165.0,
                child: GeneratedIColetaContainer2Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 40.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 18.0,
                child: GeneratedDigiteseunomeWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 50.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 112.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 21.0,
                child: GeneratedCriarContaWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 50.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 24.0,
                child: GeneratedCancelarWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 14.0,
                child: GeneratedNomecompletoWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 233.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 40.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 18.0,
                child: GeneratedDigiteseuemailWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 14.0,
                child: GeneratedEndereodeemailWidget1(),
              ),
              Positioned(
                left: 36.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 40.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 34.0,
                child: GeneratedDigitesuasenhaWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 17.0,
                child: GeneratedSenhaWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 40.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 353.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 18.0,
                child: GeneratedConfirmesuasenhaWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 88.0,
                height: 14.0,
                child: GeneratedConfirmeasenhaWidget(),
              ),
              Positioned(
                left: 243.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconocultarsenha1Widget(),
              ),
              Positioned(
                left: 243.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconocultarsenha2Widget(),
              )
            ]),
      ),
    ));
  }
}
