import 'package:flutter/material.dart';
import 'package:flutterapp/icoletaapp/generatedtelainicialwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelainicialwidget/generated/GeneratedCadastrarWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelainicialwidget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelainicialwidget/generated/GeneratedIColetabranco1Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelainicialwidget/generated/GeneratedRectangle2Widget.dart';

/* Frame Tela Inicial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelaInicialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 320.0,
        height: 568.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 19, 22, 25),
                ),
              ),
              Positioned(
                left: 50.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 52.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 52.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 121.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 24.0,
                child: GeneratedCadastrarWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 24.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 230.0,
                child: GeneratedIColetabranco1Widget(),
              )
            ]),
      ),
    ));
  }
}
