import 'package:flutter/material.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedAindanotemumacontaWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedDigitesuasenhaWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedCliqueaquiWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedIconemail1Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedSeuemailWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedIconocultarsenha3Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedIconsenhatrancar1Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedCadastrarWidget1.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedEsqueceusenhaWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedEndereodeemailWidget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedIColetaContainer1Widget.dart';
import 'package:flutterapp/icoletaapp/generatedtelaloginwidget/generated/GeneratedSenhaWidget.dart';

/* Frame Tela Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelaLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 320.0,
        height: 568.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 66, 190, 165),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 163.0,
                child: GeneratedIColetaContainer1Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 40.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 40.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 50.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 24.0,
                child: GeneratedLoginWidget1(),
              ),
              Positioned(
                left: 72.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 18.0,
                child: GeneratedSeuemailWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 18.0,
                child: GeneratedDigitesuasenhaWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 15.0,
                child: GeneratedAindanotemumacontaWidget(),
              ),
              Positioned(
                left: 123.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 15.0,
                child: GeneratedEsqueceusenhaWidget(),
              ),
              Positioned(
                left: 206.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 18.0,
                child: GeneratedCadastrarWidget1(),
              ),
              Positioned(
                left: 225.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 15.0,
                child: GeneratedCliqueaquiWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 14.0,
                child: GeneratedEndereodeemailWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 17.0,
                child: GeneratedSenhaWidget(),
              ),
              Positioned(
                left: 247.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIconocultarsenha3Widget(),
              ),
              Positioned(
                left: 45.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 26.0,
                child: GeneratedIconemail1Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 289.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 21.0,
                child: GeneratedIconsenhatrancar1Widget(),
              )
            ]),
      ),
    ));
  }
}
